// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEj3mAjiLYYcOemoB6th3s2OiEp-fEd2Q',
    appId: '1:906492867821:web:23291c2ad10a56591748e4',
    messagingSenderId: '906492867821',
    projectId: 'todo-master-ce2e7',
    authDomain: 'todo-master-ce2e7.firebaseapp.com',
    storageBucket: 'todo-master-ce2e7.appspot.com',
    measurementId: 'G-308FXEMXP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxq-fO8y7S3YPIOu6r15J9CTARsR5R1c0',
    appId: '1:906492867821:android:337a63a7a04b589e1748e4',
    messagingSenderId: '906492867821',
    projectId: 'todo-master-ce2e7',
    storageBucket: 'todo-master-ce2e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBArZrXS6k-BDJVIdJDkedwK8mksJ1z5w',
    appId: '1:906492867821:ios:80cf2385f8bd08de1748e4',
    messagingSenderId: '906492867821',
    projectId: 'todo-master-ce2e7',
    storageBucket: 'todo-master-ce2e7.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBArZrXS6k-BDJVIdJDkedwK8mksJ1z5w',
    appId: '1:906492867821:ios:80cf2385f8bd08de1748e4',
    messagingSenderId: '906492867821',
    projectId: 'todo-master-ce2e7',
    storageBucket: 'todo-master-ce2e7.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEj3mAjiLYYcOemoB6th3s2OiEp-fEd2Q',
    appId: '1:906492867821:web:cee50272885ed0321748e4',
    messagingSenderId: '906492867821',
    projectId: 'todo-master-ce2e7',
    authDomain: 'todo-master-ce2e7.firebaseapp.com',
    storageBucket: 'todo-master-ce2e7.appspot.com',
    measurementId: 'G-8SYBLD18XP',
  );

}